### ISSUE TITLE
Old dependency Google Play publishing warning

### ISSUE THREAD

**Issue by Petr-Kubista** [clostra/newnode#107]
In a recent update of our app using NewNode, we got a warning about an old SDK being used by your library:

com.bugsnag:bugsnag-android:4.5.0

It is necessary to update this to at least 4.7.0+, or your library will prevent apps from being updated on Google Play by 12. January 2022.

**Comment by ghazel** [comment]
Fixed in 8aceab894a558229b1ece61ecdff5dedc88cc10a
