### ISSUE TITLE
jCenter deprecation

### ISSUE THREAD

**Issue by Petr-Kubista** [clostra/newnode#108]
jCenter maven repository is being deprecated and won't be accessible in future gradle versions. Could you please migrate to another maven repo? Thanks!

**Comment by flyinhome** [comment]
It looks to me like they changed their minds and decided to make jCenter accessible (on a read-only basis) indefinitely.   Does this help, or at least make moving to another maven repo less urgent?  Thanks.

https://blog.gradle.org/jcenter-shutdown

**Comment by Petr-Kubista** [comment]
Thanks for your response. Unfortunately, Google's Gradle plugin made the use of jCenter deprecated as well, making us unable to upgrade to a newer version (also mentioned in the article):

> Gradle 7.0 will also deprecate the use of jcenter() to resolve dependencies. You will still be able to use JCenter as a repository, but Gradle will emit a deprecation warning. The jcenter() method will be removed in the next major release.

Further down, there's a mention of a deadline when there's no guarantee of jcenter() still working:

> Based on the current timeline, builds that use JCenter will be able to resolve dependencies until February 1, 2022 without changes. After that date, there are no guarantees that you will be able to build your software if you continue to use JCenter.

**Comment by flyinhome** [comment]
Ok, thanks.   I'll see about using mavenCentral instead and get the repo updated once that's been verified to work.
