### ISSUE TITLE
Swift Package Manager integration issues

### ISSUE THREAD

**Issue by Petr-Kubista** [clostra/newnode#109]
While moving from CocoaPods to SPM, we came onto a couple issues with NewNode.

First of all, we can't use the feature "Up to next major version" when specifying 1.9.8 as lower bounds version, or exact version.
Xcode package resolution fails with a message "Couldn't update repository submodules" at the step "Checking out 1.9.8".
Adding the dependency at master branch works.

When adding it as master branch, build fails with the following error:
`
Missing path (/Users/username/Library/Developer/Xcode/DerivedData/RFE-bjpqxpyfdqtzrxbstowuyrfgmuat/SourcePackages/checkouts/newnode/NewNode.xcframework/ios-arm64/Headers) from XCFramework 'NewNode.xcframework' as defined by 'HeadersPath' in its 'Info.plist' file
`

**Comment by ghazel** [comment]
Should be fixed by 4847b0b6f74a4aa71277f306482a7d070b63abb2
