### ISSUE TITLE
ios crashes - newnode_init

### ISSUE THREAD

**Issue by voxvox** [clostra/newnode#110]
Hi,
we see this crash even with the latest NewNode version in the Firebase crashlytics feedback across various ios versions. We can not repicate at our side. Details here:

`Key: crash_info_entry_0
Value: Assertion failed: (0), function pdie, file log.c, line 44. `

Stacktrace:
` Crashed: Thread #1
SIGABRT ABORT 0x00000001bc2469e8
Crashed: Thread
0  libsystem_kernel.dylib         0x69e8 __pthread_kill + 8
1  libsystem_pthread.dylib        0x10824 pthread_kill + 208
2  libsystem_c.dylib              0x1f0b4 abort + 120
3  libsystem_c.dylib              0x726ac err + 294
4  NewNode                        0x613d4 newnode_init + 38600
5  NewNode                        0x635bc newnode_init + 47280
6  NewNode                        0x639ac newnode_init + 48288
7  NewNode                        0x7fa8c newnode_init + 163200
8  NewNode                        0x67f14 newnode_init + 66056
9  NewNode                        0x57d74 newnode_init + 104
10 NewNode                        0x57e3c newnode_init + 304
11 NewNode                        0x69138 newnode_init + 70700
12 libsystem_pthread.dylib        0x63a4 _pthread_start + 116
13 libsystem_pthread.dylib        0x49fc thread_start + 8`

**Comment by ghazel** [comment]
Can you get debug logs as well?

**Comment by voxvox** [comment]
Hi Greg, this info is not available through Firebase crashlytics.

**Comment by ghazel** [comment]
Fixed in https://github.com/clostra/newnode/commit/ecb698848137f5d3ea43ad5a6e6e68b21c7706ee
