### ISSUE TITLE
Feature request: opt out from searching near by devices and using Bluetooth on iOS

### ISSUE THREAD

**Issue by spring-reverb** [clostra/newnode#114]
Can you please provide a way to opt out from searching devices and using Bluetooth for iOS? It's already possible for Android version of library.

We understand that newnode works better when it's possible to perform p2p communication between devices without using internet. However, it may be considered as a privacy issue by our users.

**Comment by ghazel** [comment]
This has been implemented.

**Comment by isnifer** [comment]
@ghazel do you have any reference how to avoid this on iOS?

**Comment by ghazel** [comment]
```swift
NewNodeExperimental.requestBluetoothPermission = false;
NewNodeExperimental.requestDiscoveryPermission = false;
```
