### ISSUE TITLE
iOS. NewNode proxy does not receive connections after returning app from background

### ISSUE THREAD

**Issue by spring-reverb** [clostra/newnode#116]
We have this scenario:

- open our flutter app (inits the newnode as a proxy, all requests go through that proxy)
- perform some requests (works fine)
- move app to background
- lock the screen for 10-30 seconds
- unlock the screen
- open app again
- perform request: all requests fail with "connection refused" error.

It seems that iOS closes proxy socket opened by NewNode. We do not have this kind of error if we omit proxying data through newnode.

We can add some kind of workaround in our app to reinit proxy, but I do not see any API to call for that matter.

**Comment by spring-reverb** [comment]
We tried to use generic http proxy (local tinyproxy instance) and we _do not_ have this kind of errors.

We researched NN code (client.c), but haven't found any ways to reinitialize newnode. 

@ghazel Can you, please, help us in dealing with this issue? It's very important for us to deal with it rapidly.

**Comment by ghazel** [comment]
You are running tinyproxy on the iOS device itself, as part of your app?

**Comment by spring-reverb** [comment]
Of couse not. We just tried to use some generic http proxy to prove that the issue is not in our proxy client code

**Comment by ghazel** [comment]
This is the same issue as https://github.com/clostra/newnode/issues/96

**Comment by spring-reverb** [comment]
Is there a workaround available? We can add some code to foreground/background event handlers to init/deinit newnode for iOS. 

In essence, the app is unusable after returning from the locked screen. That's the usual case for our users: they checkout the app content, switch to something else, lock the screen, check the app again.

**Comment by ghazel** [comment]
There is a fix in progress, but no work-around currently. (You could kill your app when backgrounded, but that might be too disruptive)

**Comment by ghazel** [comment]
Fixed. Will be released shortly.

**Comment by ghazel** [comment]
Released in [2.0.4](https://github.com/clostra/newnode/releases/tag/2.0.4)
