### ISSUE TITLE
bug in the client

### ISSUE THREAD

**Issue by Slava2001** [clostra/newnode#126]
Reproducer:
• launch the newNode client
• start the web server
• connect to the web server through the client (configure the client as a proxy server in the browser used)
• disable the web server
• refresh the page in the browser

![image](https://user-images.githubusercontent.com/45189467/175030005-3a37680f-11b7-46c4-a44d-2746c9eec16c.png)

The error occurs because a non-valid pointer is passed to the evhttp_connection_free_on_completion function.
I added the following code to catch her:
![image](https://user-images.githubusercontent.com/45189467/175032182-284c0206-e1ca-4b54-82a7-72b0d7eec763.png)

As a server, I used the Python SimpleHTTPServer module, and connected to it via an external ip address.
os Ubuntu.
I hope that I helped in some way, I am ready to provide more information if necessary.

**Comment by nikonru** [comment]
Oh shit, I am sorry, thanks Slava, it was a critical bug in our system. Now when we fixed it, our android users can use NewNode again.

**Comment by ghazel** [comment]
I believe this was fixed. Can you try now?
