### ISSUE TITLE
Travis CI Mac OS X build

### ISSUE THREAD

**Issue by shalunov** [clostra/newnode#24]
https://docs.travis-ci.com/user/osx-ci-environment/

Right now, the Linux build has made master very hard to work with from Mac OS X.

Having a Mac OS X build on Travis will make this much easier.

**Comment by shalunov** [comment]
@inetic https://travis-ci.org/clostra/dcdn/builds/235756448 fails

**Comment by shalunov** [comment]
```
Ie 57:28| p:0x61400000b240 error_cb 1
5678 HTTP error code: 502
```

**Comment by shalunov** [comment]
Out of a dozen runs on my machine, all have passed.

**Comment by inetic** [comment]
Ah, yes, that seems to be still the same issue with the python HTTP server not being able to serve "many" (although "many" is really only 12 in this case) concurrent requests. Just to explain the error message:

```
Ie 57:28| p:0x61400000b240 error_cb 1
5678 HTTP error code: 502
```

The 'Ie' at the beginning of the line means that the message comes from the injector ('e' stands for `stderr` output). The error itself is printed [here](https://github.com/clostra/dcdn/blob/7f8595f95d298fcffd2fc2102d212354d22d2f71/injector.c#L169) and the '1' at the end of the line means that the server responded with the error EVREQ_HTTP_EOF.

The next line is just an information from curl that it received the 502 HTTP error (Bad Gateway) from injector helper.

I'm thinking about creating a small test http server based on an example in libevent.
