### ISSUE TITLE
We need a real build automation setup

### ISSUE THREAD

**Issue by vmon** [clostra/newnode#45]
I'm having problems which can be resolve we had a build automation instead of home brewed ./build.sh. For example I get this:

    Building dht.o...
    In file included from dht.cpp:1:
    In file included from /usr/include/sys/types.h:25:
/usr/include/features.h:180:3: fatal error: "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-W#warnings]
    # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
    ^
So if I drop -D_BSD_SOURCE in the source it will goes away and then I'll get 
  
    Building dht.o...
    In file included from dht.cpp:14:
    ./dht.h:5:10: fatal error: 'Block.h' file not found
     #include <Block.h>
                ^~~~~~~~~
     1 error generated.

this is my clang version

    clang version 4.0.0 (tags/RELEASE_400/final)

I know I can hack my way out but probably these are problems that others will face sooner and later, and build automation system has been invented to exactly sort out these kind of problems without human intervention.

**Comment by shalunov** [comment]
Did you do what `.travis.yml` does? In particular, did you install libBlocksRuntime?

**Comment by vmon** [comment]
Yes I did. Though when you have an build automation it check the pre-requisits and tells you about it. 
Now I'm getting another error, related to clang compile. 

    Building injector...
    In file included from injector.c:16:
    In file included from ./libutp/utp.h:31:
    ./libutp/utp_types.h:117:15: fatal error: cannot combine with previous 'type-name' declaration    specifier
    typedef uint8 bool;
                  ^
    /usr/bin/../lib/clang/4.0.0/include/stdbool.h:31:14: note: expanded from macro 'bool'
    #define bool _Bool
                 ^
    1 error generated.

I can successfuly make the libutp (with g++) this is specific to compiling injector.c

**Comment by vmon** [comment]
The problem was that I was using upstream libutp instead of clostra one. I'll add something to README about that.

Nonetheless, the issue of having a build system stands.

**Comment by shalunov** [comment]
How'd you end up with the wrong libutp? Did you do `git submodule init && git submodule update --recursive` or something like that?

**Comment by vmon** [comment]
it seems that we have to have a cmake for the android build.
 "If your native sources don’t already have a CMake build script, you need to create one yourself and include the appropriate CMake commands." https://developer.android.com/studio/projects/add-native-code.html#create-cmake-script

**Comment by shalunov** [comment]
https://github.com/clostra/dcdn/blob/09d38b56c842cf797533e6effa897c6bf80930e2/CMakeLists.txt

**Comment by shalunov** [comment]
@vmon Can you confirm that this works on a fresh checkout or post the first error?

**Comment by vmon** [comment]
I also looked at android studio and by usual process for linking an android project to c/c++ library is to use cmake, another reason we need a cmake build.
