### ISSUE TITLE
Fix libbtdht memory leaks or suppress them

### ISSUE THREAD

**Issue by inetic** [clostra/newnode#50]
After either the `injector` or `injector_helper` exits, there is a [huge list of memory leaks](https://pastebin.com/BDi0Zkn2) reported from `ASan` inside the `libbtdht` library. This makes it very hard to spot memory leaks inside the `dcdn` if we were to introduce some.

So far I've found two causes of this, first one being that blocks of memory allocated [here](https://github.com/clostra/libbtdht/blob/51fc2e78547cceb0a88604f53696b0c686c2eb74/src/blockallocator.cpp#L30) are not freed in the destructor of the [BlockAllocator](https://github.com/clostra/libbtdht/blob/51fc2e78547cceb0a88604f53696b0c686c2eb74/src/blockallocator.h#L24) struct (nor anywhere else).

The second problem is that the main object of type [DhtImpl](https://github.com/clostra/libbtdht/blob/51fc2e78547cceb0a88604f53696b0c686c2eb74/src/DhtImpl.h#L1795) is never destroyed (Note: objects of type `BlockAllocator` are also members of this class). We do try to destroy it [here](https://github.com/clostra/dcdn/blob/e32b1ea0d8952881774f6aeab7ccdc64440d3ddd/dht.cpp#L226) but reference count of that `smart_ptr` has been incremented a few times _inside libbtdht_ (e.g. [here](https://github.com/clostra/libbtdht/blob/51fc2e78547cceb0a88604f53696b0c686c2eb74/src/DhtImpl.cpp#L4370)) and thus the destruction doesn't take place.

It is not clear to me whether this destruction can be forced cleanly and so we should investigate that further. If not, then we could try to [suppress these errors](https://clang.llvm.org/docs/AddressSanitizer.html#issue-suppression) as this problem only appears on app exit (or switch to another library).

**Comment by shalunov** [comment]
uTorrent uses `libbtdht` so it's unlikely that these are real leaks that would accumulate; more likely they'd go away on timer, right?

**Comment by inetic** [comment]
You're right, those that I looked at don't accumulate. However the [list](https://pastebin.com/BDi0Zkn2) has 689 leaks in it (and I've seen this number bigger in actual tests) so it's quite hard to tell whether all of them would be gone if the above two were fixed.
