### ISSUE TITLE
CI takes 40 minutes to finish

### ISSUE THREAD

**Issue by shalunov** [clostra/newnode#53]
<img width="623" alt="screen shot 2017-06-08 at 2 31 45 pm" src="https://user-images.githubusercontent.com/20090/26951779-50258ad2-4c57-11e7-9da7-0a06eca3674f.png">

**Comment by shalunov** [comment]
Possible that it just has to wait in line for a Mac worker machine this whole time?..

<img width="1055" alt="screen shot 2017-06-08 at 2 58 53 pm" src="https://user-images.githubusercontent.com/20090/26952630-30a880f2-4c5b-11e7-9d03-7a6845416fd8.png">
<img width="1057" alt="screen shot 2017-06-08 at 2 59 10 pm" src="https://user-images.githubusercontent.com/20090/26952629-30a025d8-4c5b-11e7-9421-5b13b4d4a409.png">

**Comment by shalunov** [comment]
<img width="855" alt="screen shot 2017-06-08 at 3 02 53 pm" src="https://user-images.githubusercontent.com/20090/26952739-9ce28862-4c5b-11e7-9759-0964f2f4b38a.png">

**Comment by inetic** [comment]
Yes, I've seen this as well. OS X build just doesn't start for a long time. Once it even happened to me that the build started, but somewhere in the middle it stopped and the above "Hang tight, the log cannot be shown until the build started." showed up. But then if I waited long enough it started again and finished. My guess is that they (Travis) don't have enough Macs and we have to wait in line, plus they sometimes restart it for maintenance.

**Comment by shalunov** [comment]
People say that this is what it is and that paying Travis doesn't help either. https://github.com/travis-ci/travis-ci/issues/7304

Separately, Travis Mac builds are slow (https://github.com/travis-ci/travis-ci/issues/6095), but the main problem is the backlog.

**Comment by shalunov** [comment]
Looks like it's a question of how much Travis pays MacStadium. https://www.macstadium.com/blog/how-travis-ci-halved-boot-times-for-os-x-and-ios-testing-at-macstadium/

Circle CI has Mac support. Builds there take ~10 minutes, even after a recent improvement.

![](https://circleci.com/blog/media/4-26-17%20line%20chart%20git.png)

**Comment by shalunov** [comment]
Not worth paying for and setting up CircleCI given that it's still slow, at least not until we have a much more clear need.
