### ISSUE TITLE
build.android.sh fails to build libbtdht with 'INT64_MAX' macro redefined'

### ISSUE THREAD

**Issue by vmon** [clostra/newnode#68]
In file included from dht.cpp:7:
   In file included from libbtdht/src/dht.h:26:
   libbtdht/btutils/src/utypes.h:40:9: fatal error: 'INT64_MAX' macro redefined [-Wmacro-redefined]
   #define INT64_MAX 0x7fffffffffffffffLL
           ^
~/dcdn/android-toolchain-armv7-a/bin/../sysroot/usr/include/stdint.h:188:9: note: previous definition is      here
     #define INT64_MAX        (INT64_C(9223372036854775807))
        ^
     1 error generated.

(Also I can't test with build anymore as there is no easy way of cleaning the android built libraries).

**Comment by shalunov** [comment]
Works in Travis Linux?..
