### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [clostra/newnode#74]
I would like to point out that identifiers like “[`__BEV_SPLICE_H__`](https://github.com/clostra/newnode/blob/7fb1ab846713b79ec93fbcc8f7d6f04781ab3ad8/bev_splice.h#L1 "Update candidate")” and “[`__NETWORK_H__`](https://github.com/clostra/newnode/blob/f546127171e0187e002592b6dcd59fda27af0ee9/network.h#L1 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by shalunov** [comment]
Does this cause you a problem? If so, what is it? The corresponding C files are C, not C++.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
