### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [clostra/newnode#75]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator") ⇒ [dht_setup](https://github.com/clostra/newnode/blob/f6d04151b492d22e4f853882ca204f5f1bc3cced/dht.c#L81)
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [Java_com_clostra_newnode_NewNode_setCacheDir](https://github.com/clostra/newnode/blob/6aa8522d28bce11fb1aa5212624edddffab6671e/android.c#L51)

**Comment by shalunov** [comment]
What should happen in a void function that gets a failure of `pthread_create()`?

**Comment by elfring** [comment]
* How do you think about to throw a Java exception in the affected function implementation?
* Would you like to call the function “`exit(error_code)`”?
