### ISSUE TITLE
Feature Request: configure NewNode to use upstream SOCKS proxy

### ISSUE THREAD

**Issue by n8fr8** [clostra/newnode#85]
In some cases, a user may want to have NewNode traffic be sent through a third-party proxy service like Tor. To do so, NewNode would need to support connecting through an upstream SOCKS proxy.

Any thoughts on the possibility of this?

**Comment by shalunov** [comment]
We have considered this internally, it has just been a matter of prioritization. Let this issue be a record of the request.

**Comment by ghazel** [comment]
NewNode uses UDP, but Tor does not support UDP. The SOCKS server in Tor does not have the UDP ASSOCIATE feature (and many SOCKS servers do not).

**Comment by n8fr8** [comment]
Understood. Still might be useful to support a SOCKS proxy, like those offered by other services / transports that could help reduce tracking / identification as "newnode" traffic. This is not essential for us right now, but could be useful. Thanks!
