### ISSUE TITLE
iOS WKWebView does not work

### ISSUE THREAD

**Issue by n8fr8** [clostra/newnode#86]
Apple has deprecated the use of UIWebView:
https://forums.developer.apple.com/thread/122114

NewNode needs to support WKWebView instead:
https://developer.apple.com/news/?id=12232019b

**Comment by ghazel** [comment]
`WKWebView` does not support web proxies, so this example would not work.

**Comment by ghazel** [comment]
https://github.com/OnionBrowser/OnionBrowser/issues/47

**Comment by n8fr8** [comment]
We are the maintainer / developers of Onion Browser, so I understand the issue well. 

However, since Apple is forcing us all to move to WKWebView, what is the solution moving forward for integration with NewNode? To write code that uses the proxy directly?

**Comment by m4mb01t4l14n0** [comment]
https://developer.apple.com/news/?id=12232019b

**Comment by nithinnizam** [comment]
We are also facing this issue, any workarounds or fix coming soon?
