### ISSUE TITLE
Is this really a VPN sdk?

### ISSUE THREAD

**Issue by althaf-mobomo** [clostra/newnode#88]
I'm trying to integrate a VPN sdk into my Android app. I saw in your site stating your service as "Censorship-Proof". But the sample Android app provided here doesn't do anything. If you try to access any websites blocked in your region, it won't work. 
Also only code that's required to integrate the SDK is " NewNode.init()". Would this work with any networking libraries that we use?
"

**Comment by ghazel** [comment]
`NewNode.init()` sets the application-wide proxy environment variables (`socksProxyHost`/`Port`, `proxyHost`/`Port`), which networking libraries observe by default.

If you are encountering an error with a specific site or region, please contact us at support@newnode.com

**Comment by althaf-mobomo** [comment]
@ghazel Address not found error was received for "support@newnode.com". Is this the correct mail id or do you have any other support ids?

**Comment by ghazel** [comment]
Sorry, use contact@clostra.com
