### ISSUE TITLE
The missing guides: user guide to the app, developer guide

### ISSUE THREAD

**Issue by sashagutfraind** [clostra/newnode#90]
This sounds like a major new VPN technology.
We need guides and documentation about its capabilities and advantages

**Comment by spawn-guy** [comment]
I second this. I want specifics.

Is DHT used as Technology or you injected newnode swarm into standard bittorrent swarm?

LEDBAT is okay. It is a traffic shaper.

Is local mesh network implementation based on standard apple and Google APIs? Or this is something different?

What types of traffic are supported? Does it support streaming connections? Can I modify local mesh-net authorization? To limit it to my app clients only, for example and, let's say, to OTA distribution only?

**Comment by sashagutfraind** [comment]
I launched a high level page on Wikipedia: https://en.wikipedia.org/wiki/Draft:NewNode

**Comment by sashagutfraind** [comment]
NewNode uses the standard BT swarm

I don't believe it's a mesh network per se, but it uses the Android/iOS VPN APIs

Not sure about the rest

**Comment by spawn-guy** [comment]
i'm not sure that the APIs are called "VPN", but here are the links :)

Nearby Connections API https://developers.google.com/nearby/connections/overview
and
Multipeer Connectivity https://developer.apple.com/documentation/multipeerconnectivity

if implementation is based on these APIs - why implement DHT? looks like the discovery is already supported by these APIs.

both support local-peer-discovery and sending Streaming data. can't find information if it is possible to multicast a stream (or anything)

**Comment by spawn-guy** [comment]
i summon @arishal to help us figure things out
