### ISSUE TITLE
NewNode VPN on Android isn't supported on most of devices

### ISSUE THREAD

**Issue by StudioMaX** [clostra/newnode#91]
![изображение](https://user-images.githubusercontent.com/9878458/89943669-65134200-dc40-11ea-9dad-fbc25f6f504b.png)

I can't even imagine what the requirements of this application are if none of my devices are supported.
- Huawei M5 (Android 9.0, has cellular, Wi-Fi, Bluetooth)
- Huawei M3 (Android 7.0, has cellular, Wi-Fi, Bluetooth)
- Motorola Moto X (Android 6.0, has cellular, Wi-Fi, Bluetooth)
- Just APK also won't installing ("There was a problem parsing the package").

**Comment by alexfaley** [comment]
Whene I Install it on redmi note 4 I got the  message "There was problem while parsing  the package "

**Comment by pavekolchanov** [comment]
Confirmed on unlocked and rooted Redmi 4A with Android 9.0: "There was problem while parsing the package"

**Comment by whoizit** [comment]
Wileyfox Swift 2+, with Android 9, unsupported

**Comment by artyom-poptsov** [comment]
Android 7.0, unsupported.

**Comment by Zerogoki00** [comment]
Same story. I have Huawei P20 Lite (ANE-LX1).
It's unlocked and rooted and has OmniROM installed (Android 9). I can install it neither from Google Play or APK

**Comment by yuwwx** [comment]
To install the application you need Android 10 (API level 29)

**Comment by arishal** [comment]
Arina from NewNode here - the app currently requires Android 10 proxy settings. Older Android version support is upcoming.
