### ISSUE TITLE
iOS - App Store distribution failed with errors due to the NewNode library version 1.9.7 (Invalid Bundle Structure)

### ISSUE THREAD

**Issue by adarshm** [clostra/newnode#97]
We have been using NewNode library in our iOS apps. Previously, it has been integrated via the dependency manager CocoaPods. Since NewNode ended the support for CocoaPods and the latest version of the library can only be integrated using Swift Package Manager (SPM), we migrated to SPM. We were able to update (or install) the library using SPM and able to build the project with that. However, Apple doesn't allow to upload the build with the latest NewNode library to App Store. 

**Error: Invalid Bundle Structure - The binary file OUR_APP.app/Frameworks/libnewnode.a' is not permitted.** 

Here are the full details of the errors which were received when uploading the build to the App Store:

```
App Store Connect Operation Error
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file OUR_APP.app/Frameworks/libnewnode.a' is not permitted. 
Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles.
Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

App Store Connect Operation Error
ERROR ITMS-90432: "Invalid Swift Support. The file OUR_APP.app/Frameworks/libnewnode.a doesn’t have the correct file type for this location. 
Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it."
```

![newnode_xcode_upload_error](https://user-images.githubusercontent.com/2315050/104723272-0608aa80-5755-11eb-86b2-4c51393c170b.jpg)

Could you please check this issue and respond to us with your suggestions or solutions as soon as possible? 

Thanks in advance.

**Comment by adarshm** [comment]
Hi Team,

Have you got a chance to review this? Please give more priority to this. I’m eager to receive your response.

Thanks in advance!

**Comment by ghazel** [comment]
We re-enabled Cocoapods support.

**Comment by adarshm** [comment]
Thanks for the updates @ghazel 👍
